export const PERMISSIONS = {
  TENANTS_READ: 'tenants.read',
  TENANTS_CREATE: 'tenants.create',
  TENANTS_UPDATE: 'tenants.update',
  TENANTS_STATUS: 'tenants.status',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_STATUS: 'users.status',
  USERS_ROLES: 'users.roles',
  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_STATUS: 'roles.status',
  ROLES_PERMISSIONS: 'roles.permissions',
  PERMISSIONS_READ: 'permissions.read',
  RBAC_TEST: 'rbac.test',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_READ: 'products.read',
  PRODUCTS_UPDATE: 'products.update',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_READ: 'categories.read',
  CATEGORIES_UPDATE: 'categories.update',
  UNITS_CREATE: 'units.create',
  UNITS_READ: 'units.read',
  UNITS_UPDATE: 'units.update',
  WAREHOUSES_CREATE: 'warehouses.create',
  WAREHOUSES_READ: 'warehouses.read',
  WAREHOUSES_UPDATE: 'warehouses.update',
  STOCK_READ: 'stock.read',
  STOCK_ADJUST: 'stock.adjust',
  STOCK_MOVEMENTS_READ: 'stock.movements.read',
  PAYMENT_TERMS_CREATE: 'payment-terms.create',
  PAYMENT_TERMS_READ: 'payment-terms.read',
  PAYMENT_TERMS_UPDATE: 'payment-terms.update',
  PAYMENT_METHODS_CREATE: 'payment-methods.create',
  PAYMENT_METHODS_READ: 'payment-methods.read',
  PAYMENT_METHODS_UPDATE: 'payment-methods.update',
  FISCAL_POSITIONS_CREATE: 'fiscal-positions.create',
  FISCAL_POSITIONS_READ: 'fiscal-positions.read',
  FISCAL_POSITIONS_UPDATE: 'fiscal-positions.update',
  INDUSTRIES_CREATE: 'industries.create',
  INDUSTRIES_READ: 'industries.read',
  INDUSTRIES_UPDATE: 'industries.update',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_UPDATE: 'suppliers.update',
  PURCHASE_ORDERS_CREATE: 'purchase-orders.create',
  PURCHASE_ORDERS_READ: 'purchase-orders.read',
  PURCHASE_ORDERS_UPDATE: 'purchase-orders.update',
  PURCHASE_ORDERS_CONFIRM: 'purchase-orders.confirm',
  PURCHASE_ORDERS_CANCEL: 'purchase-orders.cancel',
  GOODS_RECEIPTS_CREATE: 'goods-receipts.create',
  GOODS_RECEIPTS_READ: 'goods-receipts.read',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_UPDATE: 'customers.update',
  QUOTATIONS_CREATE: 'quotations.create',
  QUOTATIONS_READ: 'quotations.read',
  QUOTATIONS_UPDATE: 'quotations.update',
  QUOTATIONS_SEND: 'quotations.send',
  QUOTATIONS_ACCEPT: 'quotations.accept',
  QUOTATIONS_REJECT: 'quotations.reject',
  QUOTATIONS_CANCEL: 'quotations.cancel',
  PROFORMA_INVOICES_CREATE: 'proforma-invoices.create',
  PROFORMA_INVOICES_READ: 'proforma-invoices.read',
  PROFORMA_INVOICES_UPDATE: 'proforma-invoices.update',
  PROFORMA_INVOICES_SEND: 'proforma-invoices.send',
  PROFORMA_INVOICES_CANCEL: 'proforma-invoices.cancel',
  SALES_ORDERS_CREATE: 'sales-orders.create',
  SALES_ORDERS_READ: 'sales-orders.read',
  SALES_ORDERS_UPDATE: 'sales-orders.update',
  SALES_ORDERS_CONFIRM: 'sales-orders.confirm',
  SALES_ORDERS_CANCEL: 'sales-orders.cancel',
  SALES_INVOICES_CREATE: 'sales-invoices.create',
  SALES_INVOICES_READ: 'sales-invoices.read',
  SALES_INVOICES_UPDATE: 'sales-invoices.update',
  SALES_INVOICES_SEND: 'sales-invoices.send',
  SALES_INVOICES_CANCEL: 'sales-invoices.cancel',
  SHIPMENTS_CREATE: 'shipments.create',
  SHIPMENTS_READ: 'shipments.read',
  SHIPMENTS_POST: 'shipments.post',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export function permissionKey(resource: string, action: string): string {
  return `${resource}.${action}`;
}

export function hasAllPermissions(
  owned: readonly string[],
  required: readonly string[],
): boolean {
  if (required.length === 0) {
    return true;
  }
  const granted = new Set(owned);
  return required.every((permission) => granted.has(permission));
}
